"""Writes sintab.h: sine over a 256-step circle in 16.16 fixed point (the CPU has no FPU)."""
import math, os

rows = []
for i in range(0, 256, 8):
    rows.append('    ' + ', '.join('%6d' % round(math.sin(2 * math.pi * k / 256) * 65536) for k in range(i, i + 8)) + ',')
text = ('// Generated by gen_sintab.py: sin(2*pi*i/256) in 16.16 fixed point.\n'
        'static const int32_t sintab[256] = {\n' + '\n'.join(rows) + '\n};\n')
open(os.path.join(os.path.dirname(os.path.abspath(__file__)), 'sintab.h'), 'w', newline='\n').write(text)
