"""Writes sintab.h: sine over a 1024-step circle in 16.16 fixed point (the CPU has no FPU)."""
import math, os

N = 1024
rows = []
for i in range(0, N, 8):
    rows.append('    ' + ', '.join('%6d' % round(math.sin(2 * math.pi * k / N) * 65536) for k in range(i, i + 8)) + ',')
text = ('// Generated by gen_sintab.py: sin(2*pi*i/%d) in 16.16 fixed point.\n'
        'static const int32_t sintab[%d] = {\n' % (N, N) + '\n'.join(rows) + '\n};\n')
open(os.path.join(os.path.dirname(os.path.abspath(__file__)), 'sintab.h'), 'w', newline='\n').write(text)
